pipeline {
    agent {
        node {
            label 'nodejs-env'
        }
    }
    stages {
        stage('Setup'){
            steps {
                cleanWs()
                checkout scm
            }
        }
        stage('Install dependencies') {
            steps {
                dir('../../') {
                    sh 'npm ci'
                }
            }
        }  
    }

    post {
        success {
            echo 'Installed successfully'
        }
        failure {
            echo 'Build failed'
        }
    }
}
