pipeline {
    agent {
        node {
            label 'nodejs-env'
        }
    }
    stages {
        stage('Setup'){
            steps {
                cleanWs()
                checkout scm
            }
        }
        stage('Install dependencies') {
            steps {
                bat 'npm ci'
            }
        }  
    }

    post {
        success {
            script {
                def status = currentBuild.result ?: 'SUCCESS'
                step([$class: 'GitHubCommitStatusSetter', 
                      contextSource: [$class: 'ManuallyEnteredCommitContextSource', context: 'Jenkins Build'],
                      statusResultSource: [$class: 'ConditionalStatusResultSource', results: [[$class: 'AnyBuildResult', state: status]]]])
            }
        }
        failure {
            script {
                def status = 'FAILURE'
                step([$class: 'GitHubCommitStatusSetter', 
                      contextSource: [$class: 'ManuallyEnteredCommitContextSource', context: 'Jenkins Build'],
                      statusResultSource: [$class: 'ConditionalStatusResultSource', results: [[$class: 'AnyBuildResult', state: status]]]])
            }
        } 
    }
}
