name: nodeJS actions

on:
  push: 
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: node install
      uses: actions/setup-node@v4
      with: 
        node-version: 21
        cache: 'npm'
    
    - run: npm ci
    - run: npm run build --if-present
    - run: npm tet


    